Repository laminas/laminas-test, pull requests merged in 2021-12, with the labels that each got.

#36 Fixes wrong module name recognation in 3.5.0
  src/PHPUnit/Constraint/IsCurrentModuleNameConstraint.php
  test/PHPUnit/Controller/AbstractControllerTestCaseTest.php
  test/_files/ModuleWithSimilarName/Test/Module.php
  test/_files/ModuleWithSimilarName/Test/config/module.config.php
  test/_files/ModuleWithSimilarName/Test/src/Controller/IndexController.php
  test/_files/ModuleWithSimilarName/TestModule/Module.php
  test/_files/ModuleWithSimilarName/TestModule/config/module.config.php
  test/_files/ModuleWithSimilarName/TestModule/src/Controller/IndexController.php
Labels: Bug

#42 Replaces unit testing with integration testing in documentation, readme, Composer description
  README.md
  composer.json
  docs/book/assertions.md
  docs/book/index.html
  docs/book/intro.md
  docs/book/phpunit.md
  mkdocs.yml
Labels: Documentation, Enhancement

#41 Drop laminas-dom for symfony/dom-crawler
  composer.json
  composer.lock
  src/PHPUnit/Controller/AbstractHttpControllerTestCase.php
  test/PHPUnit/Controller/AbstractControllerTestCaseTest.php
  test/PHPUnit/Controller/AbstractHttpControllerTestCaseTest.php
  test/_files/Baz/config/module.config.php
  test/_files/Baz/src/Baz/Controller/IndexController.php
  test/_files/Baz/view/baz/index/registerxpathnamespace.phtml
Labels: Enhancement

#47 Fix dependencies
  composer.lock
  psalm-baseline.xml
Labels: Bug

#49 Remove laminas/laminas/laminas-zendframework-bridge
  composer.json
  composer.lock
Labels: Enhancement

#52 Support for PHP 8.1
  .laminas-ci.json
  composer.json
  composer.lock
  src/PHPUnit/Controller/AbstractConsoleControllerTestCase.php
  src/PHPUnit/Controller/AbstractControllerTestCase.php
  src/Util/ModuleLoader.php
  test/ExpectedExceptionTrait.php
  test/PHPUnit/Controller/AbstractConsoleControllerTestCaseTest.php
  test/PHPUnit/Controller/AbstractControllerTestCaseTest.php
  test/PHPUnit/Controller/AbstractHttpControllerTestCaseTest.php
  test/PHPUnit/Controller/MemoryLeakTest.php
  test/PHPUnit/ModuleDependenciesTest.php
  test/PHPUnit/Util/ModuleLoaderTest.php
  test/_files/Baz/Module.php
  test/_files/Baz/config/module.config.php
  test/_files/Baz/src/Baz/Controller/IndexController.php
  test/_files/ModuleWithEvents/Module.php
  test/_files/ModuleWithNamespace/TestModule/Module.php
  test/_files/ModuleWithNamespace/TestModule/config/module.config.php
  test/_files/ModuleWithNamespace/TestModule/src/Controller/IndexController.php
  test/_files/ModuleWithSimilarName/Test/Module.php
  test/_files/ModuleWithSimilarName/Test/config/module.config.php
  test/_files/ModuleWithSimilarName/Test/src/Controller/IndexController.php
  test/_files/ModuleWithSimilarName/TestModule/Module.php
  test/_files/ModuleWithSimilarName/TestModule/config/module.config.php
  test/_files/ModuleWithSimilarName/TestModule/src/Controller/IndexController.php
  test/_files/application.config.php
  test/_files/application.config.view.php
  test/_files/application.config.with.dependencies.disabled.php
  test/_files/application.config.with.dependencies.php
  test/_files/application.config.with.shared.events.php
  test/_files/modules-path/with-subdir/Bar/Module.php
  test/_files/modules-path/with-subdir/Bar/config/module.config.php
  test/_files/modules-path/with-subdir/Bar/src/Bar/Controller/IndexController.php
  test/_files/modules-path/with-subdir/Foo/Module.php
  test/_files/modules-path/with-subdir/Foo/config/module.config.php
  test/_files/modules-path/with-subdir/Foo/src/Foo/Controller/IndexController.php
  test/bootstrap.php
Labels: Enhancement
